# Generated by Django 3.1.12 on 2025-07-18 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='start_date',
            new_name='date_of_approval',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='monthly_repayment',
            new_name='monthly_payment',
        ),
    ]
