services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: creditdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python backend/credit_system/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app/backend
      - ./data:/app/data
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=credit_system.settings

volumes:
  postgres_data:
